name: all

on: [push]

jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run build -w pkgs/lib
      - run: npm test -w pkgs/cli
  common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm test -w pkgs/common
  lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm test -w pkgs/lib
  next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: npm ci -w pkgs/next
      # - run: npm run lint -w pkgs/next # skip: https://github.com/vercel/next.js/issues/38939
      - run: npm run build -w pkgs/next
      - run: npm test -w pkgs/next
